/**
 * TcHospitalMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-06-26 Created
 */
package com.jfsoft.tchospital.mapper;

import com.jfsoft.model.TcHospital;
import com.jfsoft.model.TcHospitalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TcHospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_hospital
     */
    int countByExample(TcHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_hospital
     */
    int deleteByExample(TcHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_hospital
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_hospital
     */
    int insert(TcHospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_hospital
     */
    int insertSelective(TcHospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_hospital
     */
    List<TcHospital> selectByExample(TcHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_hospital
     */
    TcHospital selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_hospital
     */
    int updateByExampleSelective(@Param("record") TcHospital record, @Param("example") TcHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_hospital
     */
    int updateByExample(@Param("record") TcHospital record, @Param("example") TcHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_hospital
     */
    int updateByPrimaryKeySelective(TcHospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_hospital
     */
    int updateByPrimaryKey(TcHospital record);
}