/**
 * TcLogExample.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-06-26 Created
 */
package com.jfsoft.tclog.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TcLogExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tc_log
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tc_log
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tc_log
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    public TcLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * null
     * 
     * @author wanggang
     * @version 1.0 2017-06-26
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUpMechCodeIsNull() {
            addCriterion("up_mech_code is null");
            return (Criteria) this;
        }

        public Criteria andUpMechCodeIsNotNull() {
            addCriterion("up_mech_code is not null");
            return (Criteria) this;
        }

        public Criteria andUpMechCodeEqualTo(String value) {
            addCriterion("up_mech_code =", value, "upMechCode");
            return (Criteria) this;
        }

        public Criteria andUpMechCodeNotEqualTo(String value) {
            addCriterion("up_mech_code <>", value, "upMechCode");
            return (Criteria) this;
        }

        public Criteria andUpMechCodeGreaterThan(String value) {
            addCriterion("up_mech_code >", value, "upMechCode");
            return (Criteria) this;
        }

        public Criteria andUpMechCodeGreaterThanOrEqualTo(String value) {
            addCriterion("up_mech_code >=", value, "upMechCode");
            return (Criteria) this;
        }

        public Criteria andUpMechCodeLessThan(String value) {
            addCriterion("up_mech_code <", value, "upMechCode");
            return (Criteria) this;
        }

        public Criteria andUpMechCodeLessThanOrEqualTo(String value) {
            addCriterion("up_mech_code <=", value, "upMechCode");
            return (Criteria) this;
        }

        public Criteria andUpMechCodeLike(String value) {
            addCriterion("up_mech_code like", value, "upMechCode");
            return (Criteria) this;
        }

        public Criteria andUpMechCodeNotLike(String value) {
            addCriterion("up_mech_code not like", value, "upMechCode");
            return (Criteria) this;
        }

        public Criteria andUpMechCodeIn(List<String> values) {
            addCriterion("up_mech_code in", values, "upMechCode");
            return (Criteria) this;
        }

        public Criteria andUpMechCodeNotIn(List<String> values) {
            addCriterion("up_mech_code not in", values, "upMechCode");
            return (Criteria) this;
        }

        public Criteria andUpMechCodeBetween(String value1, String value2) {
            addCriterion("up_mech_code between", value1, value2, "upMechCode");
            return (Criteria) this;
        }

        public Criteria andUpMechCodeNotBetween(String value1, String value2) {
            addCriterion("up_mech_code not between", value1, value2, "upMechCode");
            return (Criteria) this;
        }

        public Criteria andUpMechNameIsNull() {
            addCriterion("up_mech_name is null");
            return (Criteria) this;
        }

        public Criteria andUpMechNameIsNotNull() {
            addCriterion("up_mech_name is not null");
            return (Criteria) this;
        }

        public Criteria andUpMechNameEqualTo(String value) {
            addCriterion("up_mech_name =", value, "upMechName");
            return (Criteria) this;
        }

        public Criteria andUpMechNameNotEqualTo(String value) {
            addCriterion("up_mech_name <>", value, "upMechName");
            return (Criteria) this;
        }

        public Criteria andUpMechNameGreaterThan(String value) {
            addCriterion("up_mech_name >", value, "upMechName");
            return (Criteria) this;
        }

        public Criteria andUpMechNameGreaterThanOrEqualTo(String value) {
            addCriterion("up_mech_name >=", value, "upMechName");
            return (Criteria) this;
        }

        public Criteria andUpMechNameLessThan(String value) {
            addCriterion("up_mech_name <", value, "upMechName");
            return (Criteria) this;
        }

        public Criteria andUpMechNameLessThanOrEqualTo(String value) {
            addCriterion("up_mech_name <=", value, "upMechName");
            return (Criteria) this;
        }

        public Criteria andUpMechNameLike(String value) {
            addCriterion("up_mech_name like", value, "upMechName");
            return (Criteria) this;
        }

        public Criteria andUpMechNameNotLike(String value) {
            addCriterion("up_mech_name not like", value, "upMechName");
            return (Criteria) this;
        }

        public Criteria andUpMechNameIn(List<String> values) {
            addCriterion("up_mech_name in", values, "upMechName");
            return (Criteria) this;
        }

        public Criteria andUpMechNameNotIn(List<String> values) {
            addCriterion("up_mech_name not in", values, "upMechName");
            return (Criteria) this;
        }

        public Criteria andUpMechNameBetween(String value1, String value2) {
            addCriterion("up_mech_name between", value1, value2, "upMechName");
            return (Criteria) this;
        }

        public Criteria andUpMechNameNotBetween(String value1, String value2) {
            addCriterion("up_mech_name not between", value1, value2, "upMechName");
            return (Criteria) this;
        }

        public Criteria andUpDateIsNull() {
            addCriterion("up_date is null");
            return (Criteria) this;
        }

        public Criteria andUpDateIsNotNull() {
            addCriterion("up_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpDateEqualTo(Date value) {
            addCriterionForJDBCDate("up_date =", value, "upDate");
            return (Criteria) this;
        }

        public Criteria andUpDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("up_date <>", value, "upDate");
            return (Criteria) this;
        }

        public Criteria andUpDateGreaterThan(Date value) {
            addCriterionForJDBCDate("up_date >", value, "upDate");
            return (Criteria) this;
        }

        public Criteria andUpDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("up_date >=", value, "upDate");
            return (Criteria) this;
        }

        public Criteria andUpDateLessThan(Date value) {
            addCriterionForJDBCDate("up_date <", value, "upDate");
            return (Criteria) this;
        }

        public Criteria andUpDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("up_date <=", value, "upDate");
            return (Criteria) this;
        }

        public Criteria andUpDateIn(List<Date> values) {
            addCriterionForJDBCDate("up_date in", values, "upDate");
            return (Criteria) this;
        }

        public Criteria andUpDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("up_date not in", values, "upDate");
            return (Criteria) this;
        }

        public Criteria andUpDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("up_date between", value1, value2, "upDate");
            return (Criteria) this;
        }

        public Criteria andUpDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("up_date not between", value1, value2, "upDate");
            return (Criteria) this;
        }

        public Criteria andUpTypeIsNull() {
            addCriterion("up_type is null");
            return (Criteria) this;
        }

        public Criteria andUpTypeIsNotNull() {
            addCriterion("up_type is not null");
            return (Criteria) this;
        }

        public Criteria andUpTypeEqualTo(String value) {
            addCriterion("up_type =", value, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeNotEqualTo(String value) {
            addCriterion("up_type <>", value, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeGreaterThan(String value) {
            addCriterion("up_type >", value, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeGreaterThanOrEqualTo(String value) {
            addCriterion("up_type >=", value, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeLessThan(String value) {
            addCriterion("up_type <", value, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeLessThanOrEqualTo(String value) {
            addCriterion("up_type <=", value, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeLike(String value) {
            addCriterion("up_type like", value, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeNotLike(String value) {
            addCriterion("up_type not like", value, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeIn(List<String> values) {
            addCriterion("up_type in", values, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeNotIn(List<String> values) {
            addCriterion("up_type not in", values, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeBetween(String value1, String value2) {
            addCriterion("up_type between", value1, value2, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeNotBetween(String value1, String value2) {
            addCriterion("up_type not between", value1, value2, "upType");
            return (Criteria) this;
        }

        public Criteria andUpStatusIsNull() {
            addCriterion("up_status is null");
            return (Criteria) this;
        }

        public Criteria andUpStatusIsNotNull() {
            addCriterion("up_status is not null");
            return (Criteria) this;
        }

        public Criteria andUpStatusEqualTo(Boolean value) {
            addCriterion("up_status =", value, "upStatus");
            return (Criteria) this;
        }

        public Criteria andUpStatusNotEqualTo(Boolean value) {
            addCriterion("up_status <>", value, "upStatus");
            return (Criteria) this;
        }

        public Criteria andUpStatusGreaterThan(Boolean value) {
            addCriterion("up_status >", value, "upStatus");
            return (Criteria) this;
        }

        public Criteria andUpStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("up_status >=", value, "upStatus");
            return (Criteria) this;
        }

        public Criteria andUpStatusLessThan(Boolean value) {
            addCriterion("up_status <", value, "upStatus");
            return (Criteria) this;
        }

        public Criteria andUpStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("up_status <=", value, "upStatus");
            return (Criteria) this;
        }

        public Criteria andUpStatusIn(List<Boolean> values) {
            addCriterion("up_status in", values, "upStatus");
            return (Criteria) this;
        }

        public Criteria andUpStatusNotIn(List<Boolean> values) {
            addCriterion("up_status not in", values, "upStatus");
            return (Criteria) this;
        }

        public Criteria andUpStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("up_status between", value1, value2, "upStatus");
            return (Criteria) this;
        }

        public Criteria andUpStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("up_status not between", value1, value2, "upStatus");
            return (Criteria) this;
        }
    
}


    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tc_log
     */
    public static class Criteria extends GeneratedCriteria {


        protected Criteria() {
            super();
        }
    
}


    /**
     * null
     * 
     * @author wanggang
     * @version 1.0 2017-06-26
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    
}


}
