/**
 * TcAreacodeMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-06-26 Created
 */
package com.jfsoft.tcareacode.mapper;

import com.jfsoft.model.TcAreacode;
import com.jfsoft.model.TcAreacodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TcAreacodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_areacode
     */
    int countByExample(TcAreacodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_areacode
     */
    int deleteByExample(TcAreacodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_areacode
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_areacode
     */
    int insert(TcAreacode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_areacode
     */
    int insertSelective(TcAreacode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_areacode
     */
    List<TcAreacode> selectByExample(TcAreacodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_areacode
     */
    TcAreacode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_areacode
     */
    int updateByExampleSelective(@Param("record") TcAreacode record, @Param("example") TcAreacodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_areacode
     */
    int updateByExample(@Param("record") TcAreacode record, @Param("example") TcAreacodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_areacode
     */
    int updateByPrimaryKeySelective(TcAreacode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_areacode
     */
    int updateByPrimaryKey(TcAreacode record);
}