/**
 * TcLisPatientinfoExample.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-06-26 Created
 */
package com.jfsoft.tclispatientinfo.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TcLisPatientinfoExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tc_lis_patientinfo
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tc_lis_patientinfo
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tc_lis_patientinfo
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    public TcLisPatientinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * null
     * 
     * @author wanggang
     * @version 1.0 2017-06-26
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeIsNull() {
            addCriterion("hospital_code is null");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeIsNotNull() {
            addCriterion("hospital_code is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeEqualTo(String value) {
            addCriterion("hospital_code =", value, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeNotEqualTo(String value) {
            addCriterion("hospital_code <>", value, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeGreaterThan(String value) {
            addCriterion("hospital_code >", value, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_code >=", value, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeLessThan(String value) {
            addCriterion("hospital_code <", value, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeLessThanOrEqualTo(String value) {
            addCriterion("hospital_code <=", value, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeLike(String value) {
            addCriterion("hospital_code like", value, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeNotLike(String value) {
            addCriterion("hospital_code not like", value, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeIn(List<String> values) {
            addCriterion("hospital_code in", values, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeNotIn(List<String> values) {
            addCriterion("hospital_code not in", values, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeBetween(String value1, String value2) {
            addCriterion("hospital_code between", value1, value2, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeNotBetween(String value1, String value2) {
            addCriterion("hospital_code not between", value1, value2, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andPatinfoidIsNull() {
            addCriterion("PatInfoId is null");
            return (Criteria) this;
        }

        public Criteria andPatinfoidIsNotNull() {
            addCriterion("PatInfoId is not null");
            return (Criteria) this;
        }

        public Criteria andPatinfoidEqualTo(Integer value) {
            addCriterion("PatInfoId =", value, "patinfoid");
            return (Criteria) this;
        }

        public Criteria andPatinfoidNotEqualTo(Integer value) {
            addCriterion("PatInfoId <>", value, "patinfoid");
            return (Criteria) this;
        }

        public Criteria andPatinfoidGreaterThan(Integer value) {
            addCriterion("PatInfoId >", value, "patinfoid");
            return (Criteria) this;
        }

        public Criteria andPatinfoidGreaterThanOrEqualTo(Integer value) {
            addCriterion("PatInfoId >=", value, "patinfoid");
            return (Criteria) this;
        }

        public Criteria andPatinfoidLessThan(Integer value) {
            addCriterion("PatInfoId <", value, "patinfoid");
            return (Criteria) this;
        }

        public Criteria andPatinfoidLessThanOrEqualTo(Integer value) {
            addCriterion("PatInfoId <=", value, "patinfoid");
            return (Criteria) this;
        }

        public Criteria andPatinfoidIn(List<Integer> values) {
            addCriterion("PatInfoId in", values, "patinfoid");
            return (Criteria) this;
        }

        public Criteria andPatinfoidNotIn(List<Integer> values) {
            addCriterion("PatInfoId not in", values, "patinfoid");
            return (Criteria) this;
        }

        public Criteria andPatinfoidBetween(Integer value1, Integer value2) {
            addCriterion("PatInfoId between", value1, value2, "patinfoid");
            return (Criteria) this;
        }

        public Criteria andPatinfoidNotBetween(Integer value1, Integer value2) {
            addCriterion("PatInfoId not between", value1, value2, "patinfoid");
            return (Criteria) this;
        }

        public Criteria andTestdateIsNull() {
            addCriterion("testdate is null");
            return (Criteria) this;
        }

        public Criteria andTestdateIsNotNull() {
            addCriterion("testdate is not null");
            return (Criteria) this;
        }

        public Criteria andTestdateEqualTo(Date value) {
            addCriterionForJDBCDate("testdate =", value, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("testdate <>", value, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateGreaterThan(Date value) {
            addCriterionForJDBCDate("testdate >", value, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("testdate >=", value, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateLessThan(Date value) {
            addCriterionForJDBCDate("testdate <", value, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("testdate <=", value, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateIn(List<Date> values) {
            addCriterionForJDBCDate("testdate in", values, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("testdate not in", values, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("testdate between", value1, value2, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("testdate not between", value1, value2, "testdate");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPycodeIsNull() {
            addCriterion("pycode is null");
            return (Criteria) this;
        }

        public Criteria andPycodeIsNotNull() {
            addCriterion("pycode is not null");
            return (Criteria) this;
        }

        public Criteria andPycodeEqualTo(String value) {
            addCriterion("pycode =", value, "pycode");
            return (Criteria) this;
        }

        public Criteria andPycodeNotEqualTo(String value) {
            addCriterion("pycode <>", value, "pycode");
            return (Criteria) this;
        }

        public Criteria andPycodeGreaterThan(String value) {
            addCriterion("pycode >", value, "pycode");
            return (Criteria) this;
        }

        public Criteria andPycodeGreaterThanOrEqualTo(String value) {
            addCriterion("pycode >=", value, "pycode");
            return (Criteria) this;
        }

        public Criteria andPycodeLessThan(String value) {
            addCriterion("pycode <", value, "pycode");
            return (Criteria) this;
        }

        public Criteria andPycodeLessThanOrEqualTo(String value) {
            addCriterion("pycode <=", value, "pycode");
            return (Criteria) this;
        }

        public Criteria andPycodeLike(String value) {
            addCriterion("pycode like", value, "pycode");
            return (Criteria) this;
        }

        public Criteria andPycodeNotLike(String value) {
            addCriterion("pycode not like", value, "pycode");
            return (Criteria) this;
        }

        public Criteria andPycodeIn(List<String> values) {
            addCriterion("pycode in", values, "pycode");
            return (Criteria) this;
        }

        public Criteria andPycodeNotIn(List<String> values) {
            addCriterion("pycode not in", values, "pycode");
            return (Criteria) this;
        }

        public Criteria andPycodeBetween(String value1, String value2) {
            addCriterion("pycode between", value1, value2, "pycode");
            return (Criteria) this;
        }

        public Criteria andPycodeNotBetween(String value1, String value2) {
            addCriterion("pycode not between", value1, value2, "pycode");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(String value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(String value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(String value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(String value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(String value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(String value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLike(String value) {
            addCriterion("age like", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotLike(String value) {
            addCriterion("age not like", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<String> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<String> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(String value1, String value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(String value1, String value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeunitIsNull() {
            addCriterion("ageunit is null");
            return (Criteria) this;
        }

        public Criteria andAgeunitIsNotNull() {
            addCriterion("ageunit is not null");
            return (Criteria) this;
        }

        public Criteria andAgeunitEqualTo(String value) {
            addCriterion("ageunit =", value, "ageunit");
            return (Criteria) this;
        }

        public Criteria andAgeunitNotEqualTo(String value) {
            addCriterion("ageunit <>", value, "ageunit");
            return (Criteria) this;
        }

        public Criteria andAgeunitGreaterThan(String value) {
            addCriterion("ageunit >", value, "ageunit");
            return (Criteria) this;
        }

        public Criteria andAgeunitGreaterThanOrEqualTo(String value) {
            addCriterion("ageunit >=", value, "ageunit");
            return (Criteria) this;
        }

        public Criteria andAgeunitLessThan(String value) {
            addCriterion("ageunit <", value, "ageunit");
            return (Criteria) this;
        }

        public Criteria andAgeunitLessThanOrEqualTo(String value) {
            addCriterion("ageunit <=", value, "ageunit");
            return (Criteria) this;
        }

        public Criteria andAgeunitLike(String value) {
            addCriterion("ageunit like", value, "ageunit");
            return (Criteria) this;
        }

        public Criteria andAgeunitNotLike(String value) {
            addCriterion("ageunit not like", value, "ageunit");
            return (Criteria) this;
        }

        public Criteria andAgeunitIn(List<String> values) {
            addCriterion("ageunit in", values, "ageunit");
            return (Criteria) this;
        }

        public Criteria andAgeunitNotIn(List<String> values) {
            addCriterion("ageunit not in", values, "ageunit");
            return (Criteria) this;
        }

        public Criteria andAgeunitBetween(String value1, String value2) {
            addCriterion("ageunit between", value1, value2, "ageunit");
            return (Criteria) this;
        }

        public Criteria andAgeunitNotBetween(String value1, String value2) {
            addCriterion("ageunit not between", value1, value2, "ageunit");
            return (Criteria) this;
        }

        public Criteria andBednumIsNull() {
            addCriterion("bednum is null");
            return (Criteria) this;
        }

        public Criteria andBednumIsNotNull() {
            addCriterion("bednum is not null");
            return (Criteria) this;
        }

        public Criteria andBednumEqualTo(String value) {
            addCriterion("bednum =", value, "bednum");
            return (Criteria) this;
        }

        public Criteria andBednumNotEqualTo(String value) {
            addCriterion("bednum <>", value, "bednum");
            return (Criteria) this;
        }

        public Criteria andBednumGreaterThan(String value) {
            addCriterion("bednum >", value, "bednum");
            return (Criteria) this;
        }

        public Criteria andBednumGreaterThanOrEqualTo(String value) {
            addCriterion("bednum >=", value, "bednum");
            return (Criteria) this;
        }

        public Criteria andBednumLessThan(String value) {
            addCriterion("bednum <", value, "bednum");
            return (Criteria) this;
        }

        public Criteria andBednumLessThanOrEqualTo(String value) {
            addCriterion("bednum <=", value, "bednum");
            return (Criteria) this;
        }

        public Criteria andBednumLike(String value) {
            addCriterion("bednum like", value, "bednum");
            return (Criteria) this;
        }

        public Criteria andBednumNotLike(String value) {
            addCriterion("bednum not like", value, "bednum");
            return (Criteria) this;
        }

        public Criteria andBednumIn(List<String> values) {
            addCriterion("bednum in", values, "bednum");
            return (Criteria) this;
        }

        public Criteria andBednumNotIn(List<String> values) {
            addCriterion("bednum not in", values, "bednum");
            return (Criteria) this;
        }

        public Criteria andBednumBetween(String value1, String value2) {
            addCriterion("bednum between", value1, value2, "bednum");
            return (Criteria) this;
        }

        public Criteria andBednumNotBetween(String value1, String value2) {
            addCriterion("bednum not between", value1, value2, "bednum");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(String value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(String value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(String value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(String value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(String value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(String value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLike(String value) {
            addCriterion("pid like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotLike(String value) {
            addCriterion("pid not like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<String> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<String> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(String value1, String value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(String value1, String value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andDptnameIsNull() {
            addCriterion("DptName is null");
            return (Criteria) this;
        }

        public Criteria andDptnameIsNotNull() {
            addCriterion("DptName is not null");
            return (Criteria) this;
        }

        public Criteria andDptnameEqualTo(String value) {
            addCriterion("DptName =", value, "dptname");
            return (Criteria) this;
        }

        public Criteria andDptnameNotEqualTo(String value) {
            addCriterion("DptName <>", value, "dptname");
            return (Criteria) this;
        }

        public Criteria andDptnameGreaterThan(String value) {
            addCriterion("DptName >", value, "dptname");
            return (Criteria) this;
        }

        public Criteria andDptnameGreaterThanOrEqualTo(String value) {
            addCriterion("DptName >=", value, "dptname");
            return (Criteria) this;
        }

        public Criteria andDptnameLessThan(String value) {
            addCriterion("DptName <", value, "dptname");
            return (Criteria) this;
        }

        public Criteria andDptnameLessThanOrEqualTo(String value) {
            addCriterion("DptName <=", value, "dptname");
            return (Criteria) this;
        }

        public Criteria andDptnameLike(String value) {
            addCriterion("DptName like", value, "dptname");
            return (Criteria) this;
        }

        public Criteria andDptnameNotLike(String value) {
            addCriterion("DptName not like", value, "dptname");
            return (Criteria) this;
        }

        public Criteria andDptnameIn(List<String> values) {
            addCriterion("DptName in", values, "dptname");
            return (Criteria) this;
        }

        public Criteria andDptnameNotIn(List<String> values) {
            addCriterion("DptName not in", values, "dptname");
            return (Criteria) this;
        }

        public Criteria andDptnameBetween(String value1, String value2) {
            addCriterion("DptName between", value1, value2, "dptname");
            return (Criteria) this;
        }

        public Criteria andDptnameNotBetween(String value1, String value2) {
            addCriterion("DptName not between", value1, value2, "dptname");
            return (Criteria) this;
        }

        public Criteria andDctnameIsNull() {
            addCriterion("DctName is null");
            return (Criteria) this;
        }

        public Criteria andDctnameIsNotNull() {
            addCriterion("DctName is not null");
            return (Criteria) this;
        }

        public Criteria andDctnameEqualTo(String value) {
            addCriterion("DctName =", value, "dctname");
            return (Criteria) this;
        }

        public Criteria andDctnameNotEqualTo(String value) {
            addCriterion("DctName <>", value, "dctname");
            return (Criteria) this;
        }

        public Criteria andDctnameGreaterThan(String value) {
            addCriterion("DctName >", value, "dctname");
            return (Criteria) this;
        }

        public Criteria andDctnameGreaterThanOrEqualTo(String value) {
            addCriterion("DctName >=", value, "dctname");
            return (Criteria) this;
        }

        public Criteria andDctnameLessThan(String value) {
            addCriterion("DctName <", value, "dctname");
            return (Criteria) this;
        }

        public Criteria andDctnameLessThanOrEqualTo(String value) {
            addCriterion("DctName <=", value, "dctname");
            return (Criteria) this;
        }

        public Criteria andDctnameLike(String value) {
            addCriterion("DctName like", value, "dctname");
            return (Criteria) this;
        }

        public Criteria andDctnameNotLike(String value) {
            addCriterion("DctName not like", value, "dctname");
            return (Criteria) this;
        }

        public Criteria andDctnameIn(List<String> values) {
            addCriterion("DctName in", values, "dctname");
            return (Criteria) this;
        }

        public Criteria andDctnameNotIn(List<String> values) {
            addCriterion("DctName not in", values, "dctname");
            return (Criteria) this;
        }

        public Criteria andDctnameBetween(String value1, String value2) {
            addCriterion("DctName between", value1, value2, "dctname");
            return (Criteria) this;
        }

        public Criteria andDctnameNotBetween(String value1, String value2) {
            addCriterion("DctName not between", value1, value2, "dctname");
            return (Criteria) this;
        }

        public Criteria andPattypeIsNull() {
            addCriterion("PatType is null");
            return (Criteria) this;
        }

        public Criteria andPattypeIsNotNull() {
            addCriterion("PatType is not null");
            return (Criteria) this;
        }

        public Criteria andPattypeEqualTo(String value) {
            addCriterion("PatType =", value, "pattype");
            return (Criteria) this;
        }

        public Criteria andPattypeNotEqualTo(String value) {
            addCriterion("PatType <>", value, "pattype");
            return (Criteria) this;
        }

        public Criteria andPattypeGreaterThan(String value) {
            addCriterion("PatType >", value, "pattype");
            return (Criteria) this;
        }

        public Criteria andPattypeGreaterThanOrEqualTo(String value) {
            addCriterion("PatType >=", value, "pattype");
            return (Criteria) this;
        }

        public Criteria andPattypeLessThan(String value) {
            addCriterion("PatType <", value, "pattype");
            return (Criteria) this;
        }

        public Criteria andPattypeLessThanOrEqualTo(String value) {
            addCriterion("PatType <=", value, "pattype");
            return (Criteria) this;
        }

        public Criteria andPattypeLike(String value) {
            addCriterion("PatType like", value, "pattype");
            return (Criteria) this;
        }

        public Criteria andPattypeNotLike(String value) {
            addCriterion("PatType not like", value, "pattype");
            return (Criteria) this;
        }

        public Criteria andPattypeIn(List<String> values) {
            addCriterion("PatType in", values, "pattype");
            return (Criteria) this;
        }

        public Criteria andPattypeNotIn(List<String> values) {
            addCriterion("PatType not in", values, "pattype");
            return (Criteria) this;
        }

        public Criteria andPattypeBetween(String value1, String value2) {
            addCriterion("PatType between", value1, value2, "pattype");
            return (Criteria) this;
        }

        public Criteria andPattypeNotBetween(String value1, String value2) {
            addCriterion("PatType not between", value1, value2, "pattype");
            return (Criteria) this;
        }

        public Criteria andLczdIsNull() {
            addCriterion("lczd is null");
            return (Criteria) this;
        }

        public Criteria andLczdIsNotNull() {
            addCriterion("lczd is not null");
            return (Criteria) this;
        }

        public Criteria andLczdEqualTo(String value) {
            addCriterion("lczd =", value, "lczd");
            return (Criteria) this;
        }

        public Criteria andLczdNotEqualTo(String value) {
            addCriterion("lczd <>", value, "lczd");
            return (Criteria) this;
        }

        public Criteria andLczdGreaterThan(String value) {
            addCriterion("lczd >", value, "lczd");
            return (Criteria) this;
        }

        public Criteria andLczdGreaterThanOrEqualTo(String value) {
            addCriterion("lczd >=", value, "lczd");
            return (Criteria) this;
        }

        public Criteria andLczdLessThan(String value) {
            addCriterion("lczd <", value, "lczd");
            return (Criteria) this;
        }

        public Criteria andLczdLessThanOrEqualTo(String value) {
            addCriterion("lczd <=", value, "lczd");
            return (Criteria) this;
        }

        public Criteria andLczdLike(String value) {
            addCriterion("lczd like", value, "lczd");
            return (Criteria) this;
        }

        public Criteria andLczdNotLike(String value) {
            addCriterion("lczd not like", value, "lczd");
            return (Criteria) this;
        }

        public Criteria andLczdIn(List<String> values) {
            addCriterion("lczd in", values, "lczd");
            return (Criteria) this;
        }

        public Criteria andLczdNotIn(List<String> values) {
            addCriterion("lczd not in", values, "lczd");
            return (Criteria) this;
        }

        public Criteria andLczdBetween(String value1, String value2) {
            addCriterion("lczd between", value1, value2, "lczd");
            return (Criteria) this;
        }

        public Criteria andLczdNotBetween(String value1, String value2) {
            addCriterion("lczd not between", value1, value2, "lczd");
            return (Criteria) this;
        }

        public Criteria andBarcodeIsNull() {
            addCriterion("barcode is null");
            return (Criteria) this;
        }

        public Criteria andBarcodeIsNotNull() {
            addCriterion("barcode is not null");
            return (Criteria) this;
        }

        public Criteria andBarcodeEqualTo(String value) {
            addCriterion("barcode =", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeNotEqualTo(String value) {
            addCriterion("barcode <>", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeGreaterThan(String value) {
            addCriterion("barcode >", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeGreaterThanOrEqualTo(String value) {
            addCriterion("barcode >=", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeLessThan(String value) {
            addCriterion("barcode <", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeLessThanOrEqualTo(String value) {
            addCriterion("barcode <=", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeLike(String value) {
            addCriterion("barcode like", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeNotLike(String value) {
            addCriterion("barcode not like", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeIn(List<String> values) {
            addCriterion("barcode in", values, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeNotIn(List<String> values) {
            addCriterion("barcode not in", values, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeBetween(String value1, String value2) {
            addCriterion("barcode between", value1, value2, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeNotBetween(String value1, String value2) {
            addCriterion("barcode not between", value1, value2, "barcode");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andRegnameIsNull() {
            addCriterion("RegName is null");
            return (Criteria) this;
        }

        public Criteria andRegnameIsNotNull() {
            addCriterion("RegName is not null");
            return (Criteria) this;
        }

        public Criteria andRegnameEqualTo(Date value) {
            addCriterionForJDBCDate("RegName =", value, "regname");
            return (Criteria) this;
        }

        public Criteria andRegnameNotEqualTo(Date value) {
            addCriterionForJDBCDate("RegName <>", value, "regname");
            return (Criteria) this;
        }

        public Criteria andRegnameGreaterThan(Date value) {
            addCriterionForJDBCDate("RegName >", value, "regname");
            return (Criteria) this;
        }

        public Criteria andRegnameGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("RegName >=", value, "regname");
            return (Criteria) this;
        }

        public Criteria andRegnameLessThan(Date value) {
            addCriterionForJDBCDate("RegName <", value, "regname");
            return (Criteria) this;
        }

        public Criteria andRegnameLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("RegName <=", value, "regname");
            return (Criteria) this;
        }

        public Criteria andRegnameIn(List<Date> values) {
            addCriterionForJDBCDate("RegName in", values, "regname");
            return (Criteria) this;
        }

        public Criteria andRegnameNotIn(List<Date> values) {
            addCriterionForJDBCDate("RegName not in", values, "regname");
            return (Criteria) this;
        }

        public Criteria andRegnameBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("RegName between", value1, value2, "regname");
            return (Criteria) this;
        }

        public Criteria andRegnameNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("RegName not between", value1, value2, "regname");
            return (Criteria) this;
        }

        public Criteria andFeenameIsNull() {
            addCriterion("FeeName is null");
            return (Criteria) this;
        }

        public Criteria andFeenameIsNotNull() {
            addCriterion("FeeName is not null");
            return (Criteria) this;
        }

        public Criteria andFeenameEqualTo(String value) {
            addCriterion("FeeName =", value, "feename");
            return (Criteria) this;
        }

        public Criteria andFeenameNotEqualTo(String value) {
            addCriterion("FeeName <>", value, "feename");
            return (Criteria) this;
        }

        public Criteria andFeenameGreaterThan(String value) {
            addCriterion("FeeName >", value, "feename");
            return (Criteria) this;
        }

        public Criteria andFeenameGreaterThanOrEqualTo(String value) {
            addCriterion("FeeName >=", value, "feename");
            return (Criteria) this;
        }

        public Criteria andFeenameLessThan(String value) {
            addCriterion("FeeName <", value, "feename");
            return (Criteria) this;
        }

        public Criteria andFeenameLessThanOrEqualTo(String value) {
            addCriterion("FeeName <=", value, "feename");
            return (Criteria) this;
        }

        public Criteria andFeenameLike(String value) {
            addCriterion("FeeName like", value, "feename");
            return (Criteria) this;
        }

        public Criteria andFeenameNotLike(String value) {
            addCriterion("FeeName not like", value, "feename");
            return (Criteria) this;
        }

        public Criteria andFeenameIn(List<String> values) {
            addCriterion("FeeName in", values, "feename");
            return (Criteria) this;
        }

        public Criteria andFeenameNotIn(List<String> values) {
            addCriterion("FeeName not in", values, "feename");
            return (Criteria) this;
        }

        public Criteria andFeenameBetween(String value1, String value2) {
            addCriterion("FeeName between", value1, value2, "feename");
            return (Criteria) this;
        }

        public Criteria andFeenameNotBetween(String value1, String value2) {
            addCriterion("FeeName not between", value1, value2, "feename");
            return (Criteria) this;
        }

        public Criteria andTesttypeIsNull() {
            addCriterion("TestType is null");
            return (Criteria) this;
        }

        public Criteria andTesttypeIsNotNull() {
            addCriterion("TestType is not null");
            return (Criteria) this;
        }

        public Criteria andTesttypeEqualTo(String value) {
            addCriterion("TestType =", value, "testtype");
            return (Criteria) this;
        }

        public Criteria andTesttypeNotEqualTo(String value) {
            addCriterion("TestType <>", value, "testtype");
            return (Criteria) this;
        }

        public Criteria andTesttypeGreaterThan(String value) {
            addCriterion("TestType >", value, "testtype");
            return (Criteria) this;
        }

        public Criteria andTesttypeGreaterThanOrEqualTo(String value) {
            addCriterion("TestType >=", value, "testtype");
            return (Criteria) this;
        }

        public Criteria andTesttypeLessThan(String value) {
            addCriterion("TestType <", value, "testtype");
            return (Criteria) this;
        }

        public Criteria andTesttypeLessThanOrEqualTo(String value) {
            addCriterion("TestType <=", value, "testtype");
            return (Criteria) this;
        }

        public Criteria andTesttypeLike(String value) {
            addCriterion("TestType like", value, "testtype");
            return (Criteria) this;
        }

        public Criteria andTesttypeNotLike(String value) {
            addCriterion("TestType not like", value, "testtype");
            return (Criteria) this;
        }

        public Criteria andTesttypeIn(List<String> values) {
            addCriterion("TestType in", values, "testtype");
            return (Criteria) this;
        }

        public Criteria andTesttypeNotIn(List<String> values) {
            addCriterion("TestType not in", values, "testtype");
            return (Criteria) this;
        }

        public Criteria andTesttypeBetween(String value1, String value2) {
            addCriterion("TestType between", value1, value2, "testtype");
            return (Criteria) this;
        }

        public Criteria andTesttypeNotBetween(String value1, String value2) {
            addCriterion("TestType not between", value1, value2, "testtype");
            return (Criteria) this;
        }

        public Criteria andTestoptIsNull() {
            addCriterion("TestOpt is null");
            return (Criteria) this;
        }

        public Criteria andTestoptIsNotNull() {
            addCriterion("TestOpt is not null");
            return (Criteria) this;
        }

        public Criteria andTestoptEqualTo(String value) {
            addCriterion("TestOpt =", value, "testopt");
            return (Criteria) this;
        }

        public Criteria andTestoptNotEqualTo(String value) {
            addCriterion("TestOpt <>", value, "testopt");
            return (Criteria) this;
        }

        public Criteria andTestoptGreaterThan(String value) {
            addCriterion("TestOpt >", value, "testopt");
            return (Criteria) this;
        }

        public Criteria andTestoptGreaterThanOrEqualTo(String value) {
            addCriterion("TestOpt >=", value, "testopt");
            return (Criteria) this;
        }

        public Criteria andTestoptLessThan(String value) {
            addCriterion("TestOpt <", value, "testopt");
            return (Criteria) this;
        }

        public Criteria andTestoptLessThanOrEqualTo(String value) {
            addCriterion("TestOpt <=", value, "testopt");
            return (Criteria) this;
        }

        public Criteria andTestoptLike(String value) {
            addCriterion("TestOpt like", value, "testopt");
            return (Criteria) this;
        }

        public Criteria andTestoptNotLike(String value) {
            addCriterion("TestOpt not like", value, "testopt");
            return (Criteria) this;
        }

        public Criteria andTestoptIn(List<String> values) {
            addCriterion("TestOpt in", values, "testopt");
            return (Criteria) this;
        }

        public Criteria andTestoptNotIn(List<String> values) {
            addCriterion("TestOpt not in", values, "testopt");
            return (Criteria) this;
        }

        public Criteria andTestoptBetween(String value1, String value2) {
            addCriterion("TestOpt between", value1, value2, "testopt");
            return (Criteria) this;
        }

        public Criteria andTestoptNotBetween(String value1, String value2) {
            addCriterion("TestOpt not between", value1, value2, "testopt");
            return (Criteria) this;
        }

        public Criteria andCheckoptIsNull() {
            addCriterion("CheckOpt is null");
            return (Criteria) this;
        }

        public Criteria andCheckoptIsNotNull() {
            addCriterion("CheckOpt is not null");
            return (Criteria) this;
        }

        public Criteria andCheckoptEqualTo(String value) {
            addCriterion("CheckOpt =", value, "checkopt");
            return (Criteria) this;
        }

        public Criteria andCheckoptNotEqualTo(String value) {
            addCriterion("CheckOpt <>", value, "checkopt");
            return (Criteria) this;
        }

        public Criteria andCheckoptGreaterThan(String value) {
            addCriterion("CheckOpt >", value, "checkopt");
            return (Criteria) this;
        }

        public Criteria andCheckoptGreaterThanOrEqualTo(String value) {
            addCriterion("CheckOpt >=", value, "checkopt");
            return (Criteria) this;
        }

        public Criteria andCheckoptLessThan(String value) {
            addCriterion("CheckOpt <", value, "checkopt");
            return (Criteria) this;
        }

        public Criteria andCheckoptLessThanOrEqualTo(String value) {
            addCriterion("CheckOpt <=", value, "checkopt");
            return (Criteria) this;
        }

        public Criteria andCheckoptLike(String value) {
            addCriterion("CheckOpt like", value, "checkopt");
            return (Criteria) this;
        }

        public Criteria andCheckoptNotLike(String value) {
            addCriterion("CheckOpt not like", value, "checkopt");
            return (Criteria) this;
        }

        public Criteria andCheckoptIn(List<String> values) {
            addCriterion("CheckOpt in", values, "checkopt");
            return (Criteria) this;
        }

        public Criteria andCheckoptNotIn(List<String> values) {
            addCriterion("CheckOpt not in", values, "checkopt");
            return (Criteria) this;
        }

        public Criteria andCheckoptBetween(String value1, String value2) {
            addCriterion("CheckOpt between", value1, value2, "checkopt");
            return (Criteria) this;
        }

        public Criteria andCheckoptNotBetween(String value1, String value2) {
            addCriterion("CheckOpt not between", value1, value2, "checkopt");
            return (Criteria) this;
        }

        public Criteria andCheckdateIsNull() {
            addCriterion("CheckDate is null");
            return (Criteria) this;
        }

        public Criteria andCheckdateIsNotNull() {
            addCriterion("CheckDate is not null");
            return (Criteria) this;
        }

        public Criteria andCheckdateEqualTo(String value) {
            addCriterion("CheckDate =", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateNotEqualTo(String value) {
            addCriterion("CheckDate <>", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateGreaterThan(String value) {
            addCriterion("CheckDate >", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateGreaterThanOrEqualTo(String value) {
            addCriterion("CheckDate >=", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateLessThan(String value) {
            addCriterion("CheckDate <", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateLessThanOrEqualTo(String value) {
            addCriterion("CheckDate <=", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateLike(String value) {
            addCriterion("CheckDate like", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateNotLike(String value) {
            addCriterion("CheckDate not like", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateIn(List<String> values) {
            addCriterion("CheckDate in", values, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateNotIn(List<String> values) {
            addCriterion("CheckDate not in", values, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateBetween(String value1, String value2) {
            addCriterion("CheckDate between", value1, value2, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateNotBetween(String value1, String value2) {
            addCriterion("CheckDate not between", value1, value2, "checkdate");
            return (Criteria) this;
        }

        public Criteria andPrintoptIsNull() {
            addCriterion("PrintOpt is null");
            return (Criteria) this;
        }

        public Criteria andPrintoptIsNotNull() {
            addCriterion("PrintOpt is not null");
            return (Criteria) this;
        }

        public Criteria andPrintoptEqualTo(String value) {
            addCriterion("PrintOpt =", value, "printopt");
            return (Criteria) this;
        }

        public Criteria andPrintoptNotEqualTo(String value) {
            addCriterion("PrintOpt <>", value, "printopt");
            return (Criteria) this;
        }

        public Criteria andPrintoptGreaterThan(String value) {
            addCriterion("PrintOpt >", value, "printopt");
            return (Criteria) this;
        }

        public Criteria andPrintoptGreaterThanOrEqualTo(String value) {
            addCriterion("PrintOpt >=", value, "printopt");
            return (Criteria) this;
        }

        public Criteria andPrintoptLessThan(String value) {
            addCriterion("PrintOpt <", value, "printopt");
            return (Criteria) this;
        }

        public Criteria andPrintoptLessThanOrEqualTo(String value) {
            addCriterion("PrintOpt <=", value, "printopt");
            return (Criteria) this;
        }

        public Criteria andPrintoptLike(String value) {
            addCriterion("PrintOpt like", value, "printopt");
            return (Criteria) this;
        }

        public Criteria andPrintoptNotLike(String value) {
            addCriterion("PrintOpt not like", value, "printopt");
            return (Criteria) this;
        }

        public Criteria andPrintoptIn(List<String> values) {
            addCriterion("PrintOpt in", values, "printopt");
            return (Criteria) this;
        }

        public Criteria andPrintoptNotIn(List<String> values) {
            addCriterion("PrintOpt not in", values, "printopt");
            return (Criteria) this;
        }

        public Criteria andPrintoptBetween(String value1, String value2) {
            addCriterion("PrintOpt between", value1, value2, "printopt");
            return (Criteria) this;
        }

        public Criteria andPrintoptNotBetween(String value1, String value2) {
            addCriterion("PrintOpt not between", value1, value2, "printopt");
            return (Criteria) this;
        }

        public Criteria andPrintdateIsNull() {
            addCriterion("PrintDate is null");
            return (Criteria) this;
        }

        public Criteria andPrintdateIsNotNull() {
            addCriterion("PrintDate is not null");
            return (Criteria) this;
        }

        public Criteria andPrintdateEqualTo(String value) {
            addCriterion("PrintDate =", value, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateNotEqualTo(String value) {
            addCriterion("PrintDate <>", value, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateGreaterThan(String value) {
            addCriterion("PrintDate >", value, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateGreaterThanOrEqualTo(String value) {
            addCriterion("PrintDate >=", value, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateLessThan(String value) {
            addCriterion("PrintDate <", value, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateLessThanOrEqualTo(String value) {
            addCriterion("PrintDate <=", value, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateLike(String value) {
            addCriterion("PrintDate like", value, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateNotLike(String value) {
            addCriterion("PrintDate not like", value, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateIn(List<String> values) {
            addCriterion("PrintDate in", values, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateNotIn(List<String> values) {
            addCriterion("PrintDate not in", values, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateBetween(String value1, String value2) {
            addCriterion("PrintDate between", value1, value2, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateNotBetween(String value1, String value2) {
            addCriterion("PrintDate not between", value1, value2, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintstateIsNull() {
            addCriterion("PrintState is null");
            return (Criteria) this;
        }

        public Criteria andPrintstateIsNotNull() {
            addCriterion("PrintState is not null");
            return (Criteria) this;
        }

        public Criteria andPrintstateEqualTo(String value) {
            addCriterion("PrintState =", value, "printstate");
            return (Criteria) this;
        }

        public Criteria andPrintstateNotEqualTo(String value) {
            addCriterion("PrintState <>", value, "printstate");
            return (Criteria) this;
        }

        public Criteria andPrintstateGreaterThan(String value) {
            addCriterion("PrintState >", value, "printstate");
            return (Criteria) this;
        }

        public Criteria andPrintstateGreaterThanOrEqualTo(String value) {
            addCriterion("PrintState >=", value, "printstate");
            return (Criteria) this;
        }

        public Criteria andPrintstateLessThan(String value) {
            addCriterion("PrintState <", value, "printstate");
            return (Criteria) this;
        }

        public Criteria andPrintstateLessThanOrEqualTo(String value) {
            addCriterion("PrintState <=", value, "printstate");
            return (Criteria) this;
        }

        public Criteria andPrintstateLike(String value) {
            addCriterion("PrintState like", value, "printstate");
            return (Criteria) this;
        }

        public Criteria andPrintstateNotLike(String value) {
            addCriterion("PrintState not like", value, "printstate");
            return (Criteria) this;
        }

        public Criteria andPrintstateIn(List<String> values) {
            addCriterion("PrintState in", values, "printstate");
            return (Criteria) this;
        }

        public Criteria andPrintstateNotIn(List<String> values) {
            addCriterion("PrintState not in", values, "printstate");
            return (Criteria) this;
        }

        public Criteria andPrintstateBetween(String value1, String value2) {
            addCriterion("PrintState between", value1, value2, "printstate");
            return (Criteria) this;
        }

        public Criteria andPrintstateNotBetween(String value1, String value2) {
            addCriterion("PrintState not between", value1, value2, "printstate");
            return (Criteria) this;
        }

        public Criteria andAreacodeIsNull() {
            addCriterion("AreaCode is null");
            return (Criteria) this;
        }

        public Criteria andAreacodeIsNotNull() {
            addCriterion("AreaCode is not null");
            return (Criteria) this;
        }

        public Criteria andAreacodeEqualTo(String value) {
            addCriterion("AreaCode =", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotEqualTo(String value) {
            addCriterion("AreaCode <>", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeGreaterThan(String value) {
            addCriterion("AreaCode >", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeGreaterThanOrEqualTo(String value) {
            addCriterion("AreaCode >=", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLessThan(String value) {
            addCriterion("AreaCode <", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLessThanOrEqualTo(String value) {
            addCriterion("AreaCode <=", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLike(String value) {
            addCriterion("AreaCode like", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotLike(String value) {
            addCriterion("AreaCode not like", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeIn(List<String> values) {
            addCriterion("AreaCode in", values, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotIn(List<String> values) {
            addCriterion("AreaCode not in", values, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeBetween(String value1, String value2) {
            addCriterion("AreaCode between", value1, value2, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotBetween(String value1, String value2) {
            addCriterion("AreaCode not between", value1, value2, "areacode");
            return (Criteria) this;
        }

        public Criteria andFilepathIsNull() {
            addCriterion("FilePath is null");
            return (Criteria) this;
        }

        public Criteria andFilepathIsNotNull() {
            addCriterion("FilePath is not null");
            return (Criteria) this;
        }

        public Criteria andFilepathEqualTo(String value) {
            addCriterion("FilePath =", value, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathNotEqualTo(String value) {
            addCriterion("FilePath <>", value, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathGreaterThan(String value) {
            addCriterion("FilePath >", value, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathGreaterThanOrEqualTo(String value) {
            addCriterion("FilePath >=", value, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathLessThan(String value) {
            addCriterion("FilePath <", value, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathLessThanOrEqualTo(String value) {
            addCriterion("FilePath <=", value, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathLike(String value) {
            addCriterion("FilePath like", value, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathNotLike(String value) {
            addCriterion("FilePath not like", value, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathIn(List<String> values) {
            addCriterion("FilePath in", values, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathNotIn(List<String> values) {
            addCriterion("FilePath not in", values, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathBetween(String value1, String value2) {
            addCriterion("FilePath between", value1, value2, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathNotBetween(String value1, String value2) {
            addCriterion("FilePath not between", value1, value2, "filepath");
            return (Criteria) this;
        }

        public Criteria andReserve1IsNull() {
            addCriterion("reserve1 is null");
            return (Criteria) this;
        }

        public Criteria andReserve1IsNotNull() {
            addCriterion("reserve1 is not null");
            return (Criteria) this;
        }

        public Criteria andReserve1EqualTo(String value) {
            addCriterion("reserve1 =", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1NotEqualTo(String value) {
            addCriterion("reserve1 <>", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1GreaterThan(String value) {
            addCriterion("reserve1 >", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1GreaterThanOrEqualTo(String value) {
            addCriterion("reserve1 >=", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1LessThan(String value) {
            addCriterion("reserve1 <", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1LessThanOrEqualTo(String value) {
            addCriterion("reserve1 <=", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1Like(String value) {
            addCriterion("reserve1 like", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1NotLike(String value) {
            addCriterion("reserve1 not like", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1In(List<String> values) {
            addCriterion("reserve1 in", values, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1NotIn(List<String> values) {
            addCriterion("reserve1 not in", values, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1Between(String value1, String value2) {
            addCriterion("reserve1 between", value1, value2, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1NotBetween(String value1, String value2) {
            addCriterion("reserve1 not between", value1, value2, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve2IsNull() {
            addCriterion("reserve2 is null");
            return (Criteria) this;
        }

        public Criteria andReserve2IsNotNull() {
            addCriterion("reserve2 is not null");
            return (Criteria) this;
        }

        public Criteria andReserve2EqualTo(String value) {
            addCriterion("reserve2 =", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2NotEqualTo(String value) {
            addCriterion("reserve2 <>", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2GreaterThan(String value) {
            addCriterion("reserve2 >", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2GreaterThanOrEqualTo(String value) {
            addCriterion("reserve2 >=", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2LessThan(String value) {
            addCriterion("reserve2 <", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2LessThanOrEqualTo(String value) {
            addCriterion("reserve2 <=", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2Like(String value) {
            addCriterion("reserve2 like", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2NotLike(String value) {
            addCriterion("reserve2 not like", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2In(List<String> values) {
            addCriterion("reserve2 in", values, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2NotIn(List<String> values) {
            addCriterion("reserve2 not in", values, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2Between(String value1, String value2) {
            addCriterion("reserve2 between", value1, value2, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2NotBetween(String value1, String value2) {
            addCriterion("reserve2 not between", value1, value2, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve3IsNull() {
            addCriterion("reserve3 is null");
            return (Criteria) this;
        }

        public Criteria andReserve3IsNotNull() {
            addCriterion("reserve3 is not null");
            return (Criteria) this;
        }

        public Criteria andReserve3EqualTo(String value) {
            addCriterion("reserve3 =", value, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3NotEqualTo(String value) {
            addCriterion("reserve3 <>", value, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3GreaterThan(String value) {
            addCriterion("reserve3 >", value, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3GreaterThanOrEqualTo(String value) {
            addCriterion("reserve3 >=", value, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3LessThan(String value) {
            addCriterion("reserve3 <", value, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3LessThanOrEqualTo(String value) {
            addCriterion("reserve3 <=", value, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3Like(String value) {
            addCriterion("reserve3 like", value, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3NotLike(String value) {
            addCriterion("reserve3 not like", value, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3In(List<String> values) {
            addCriterion("reserve3 in", values, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3NotIn(List<String> values) {
            addCriterion("reserve3 not in", values, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3Between(String value1, String value2) {
            addCriterion("reserve3 between", value1, value2, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3NotBetween(String value1, String value2) {
            addCriterion("reserve3 not between", value1, value2, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve4IsNull() {
            addCriterion("reserve4 is null");
            return (Criteria) this;
        }

        public Criteria andReserve4IsNotNull() {
            addCriterion("reserve4 is not null");
            return (Criteria) this;
        }

        public Criteria andReserve4EqualTo(String value) {
            addCriterion("reserve4 =", value, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4NotEqualTo(String value) {
            addCriterion("reserve4 <>", value, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4GreaterThan(String value) {
            addCriterion("reserve4 >", value, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4GreaterThanOrEqualTo(String value) {
            addCriterion("reserve4 >=", value, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4LessThan(String value) {
            addCriterion("reserve4 <", value, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4LessThanOrEqualTo(String value) {
            addCriterion("reserve4 <=", value, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4Like(String value) {
            addCriterion("reserve4 like", value, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4NotLike(String value) {
            addCriterion("reserve4 not like", value, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4In(List<String> values) {
            addCriterion("reserve4 in", values, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4NotIn(List<String> values) {
            addCriterion("reserve4 not in", values, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4Between(String value1, String value2) {
            addCriterion("reserve4 between", value1, value2, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4NotBetween(String value1, String value2) {
            addCriterion("reserve4 not between", value1, value2, "reserve4");
            return (Criteria) this;
        }
    
}


    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tc_lis_patientinfo
     */
    public static class Criteria extends GeneratedCriteria {


        protected Criteria() {
            super();
        }
    
}


    /**
     * null
     * 
     * @author wanggang
     * @version 1.0 2017-06-26
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    
}


}
