/**
 * TcLisPatientinfoMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-06-26 Created
 */
package com.jfsoft.tclispatientinfo.mapper;

import java.util.List;

import com.jfsoft.tclispatientinfo.model.TcLisPatientinfo;
import com.jfsoft.tclispatientinfo.model.TcLisPatientinfoExample;
import org.apache.ibatis.annotations.Param;

public interface TcLisPatientinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    int countByExample(TcLisPatientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    int deleteByExample(TcLisPatientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    int insert(TcLisPatientinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    int insertSelective(TcLisPatientinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    List<TcLisPatientinfo> selectByExample(TcLisPatientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    TcLisPatientinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    int updateByExampleSelective(@Param("record") TcLisPatientinfo record, @Param("example") TcLisPatientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    int updateByExample(@Param("record") TcLisPatientinfo record, @Param("example") TcLisPatientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    int updateByPrimaryKeySelective(TcLisPatientinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_lis_patientinfo
     */
    int updateByPrimaryKey(TcLisPatientinfo record);
}