/**
 * TcPerCheckinfoMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-06-26 Created
 */
package com.jfsoft.tc_per_checkinfo.mapper;

import com.jfsoft.model.TcPerCheckinfo;
import com.jfsoft.model.TcPerCheckinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TcPerCheckinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_per_checkinfo
     */
    int countByExample(TcPerCheckinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_per_checkinfo
     */
    int deleteByExample(TcPerCheckinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_per_checkinfo
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_per_checkinfo
     */
    int insert(TcPerCheckinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_per_checkinfo
     */
    int insertSelective(TcPerCheckinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_per_checkinfo
     */
    List<TcPerCheckinfo> selectByExample(TcPerCheckinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_per_checkinfo
     */
    TcPerCheckinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_per_checkinfo
     */
    int updateByExampleSelective(@Param("record") TcPerCheckinfo record, @Param("example") TcPerCheckinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_per_checkinfo
     */
    int updateByExample(@Param("record") TcPerCheckinfo record, @Param("example") TcPerCheckinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_per_checkinfo
     */
    int updateByPrimaryKeySelective(TcPerCheckinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_per_checkinfo
     */
    int updateByPrimaryKey(TcPerCheckinfo record);
}