/**
 * TcLogMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-06-26 Created
 */
package com.jfsoft.tclog.mapper;


import com.jfsoft.tclog.model.TcLog;
import com.jfsoft.tclog.model.TcLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TcLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    int countByExample(TcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    int deleteByExample(TcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    int insert(TcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    int insertSelective(TcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    List<TcLog> selectByExample(TcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    TcLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    int updateByExampleSelective(@Param("record") TcLog record, @Param("example") TcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    int updateByExample(@Param("record") TcLog record, @Param("example") TcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    int updateByPrimaryKeySelective(TcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_log
     */
    int updateByPrimaryKey(TcLog record);
}